server:
  port: 1001
spring:
  application:
    name: mi-eureka-client
  aop:
    auto: true #开启AOP功能
  boot:
     admin:
      url: http://localhost:1005  #应用服务监控

eureka:
  client:
    serviceUrl:
      defaultZone: http://mione:1000/eureka/ #,http://mitwo:2000/eureka/
