server:
  port: 1005
spring:
  application:
    name: Spring Boot Admin Web
  boot:
    admin:
      url: http://127.0.0.1:${server.port}
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
    client:
       metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints
security:
  user:
    name: miyaow
    password: 123

  basic:
    enabled: false

endpoints:
  health:
    sensitive: false
  cors:
    allowed-methods: GET,POST

# 引用监控限制内容Map <Key String>
info:
  artifact : mi-spring-boot-admin
  name: Spring Boot Admin
  description: 引用监控中心
  version : V1.0

logging:
  file: "traget/mi-spring-boot-admin.log"

management:
  security:
    enabled: false




