server:
  port: 1003
spring:
  application:
    name: MI-EUREKA-DISCOVERY
  boot:
    admin:
      url: http://localhost:1005 # 应用服务监控

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:1000/eureka/ #,http://mitwo:2000/eureka/

# 消费者中心 Map <Key String>
info:
  artifact : mi-eureka-discovery
  name: ${spring.application.name}
  description: 发现服务中心
  version : V1.0
